# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MyProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'HandyJSON','~>4.0.0-beta.1'
  pod 'Kingfisher'
  pod 'IBAnimatable'
  pod 'SwiftTheme'
  pod 'RxSwift','~>4.0.0-beta.0'
  pod 'RxCocoa','~>4.0.0-beta.0'
  pod 'SQLite.swift','~>0.11.4'
  pod 'SVProgressHUD'
  pod 'MJRefresh'
end
